apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-agent-verifier-dep
  namespace: user-agent-verifier-ns
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: user-agent-verifier-node
          image: dhammer25/useragentverifier:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
