apiVersion: v1
kind: Service
metadata:
  name: user-agent-verifier-svc
  namespace: user-agent-verifier-ns
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: {{ .Values.nodePort }}
      port: 3000
      targetPort: 3000
  selector:
    app: app
